version: '3.0'
services:
  mavenapp:
    springboot: mallegowda/springbootapp:1
    ports: 
    - 2906:8080
    environment:
    - MONGO_DB_HOSTNAME=mongoawsebs 
    - MONGO_DB_USERNAME=mg 
    - MONGO_DB_PASSWORD=mg@123
    networks:
    - springappbridge
  mongo:
    image: mongo
    volumes:
    - mongovol
    environment:
    - MONGO_DB_USERNAME=mg 
    - MONGO_DB_PASSWORD=mg@123
    networks:
    - springappbridge
networks:
  springappbridge:
    driver: bridge
volumes:
  mongovol:
    driver: local
